// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.PaymentPage.clickPayByPhoneBtn_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class clickPayByPhoneBtn_Map:logWriter
    {
        public void clickPayByPhoneBtn_Method(HtmlInputButton PayButton )
        {
            #region Variable Declarations
            HtmlCustom uIBtnRequestBookingCustom = this.UIVillaPlusPaymentInteWindow.UIVillaPlusPaymentDocument.UIBtnRequestBookingCustom;
            #endregion

            try
            {
                Mouse.MoveScrollWheel(PayButton, -50);
                Keyboard.SendKeys("{PGDN}");
                Keyboard.SendKeys("{END}");
                Mouse.Click(uIBtnRequestBookingCustom);
                WriteLogs("PASS : Clicked \"Pay By Phone\" Button from Payment Page. : VERIFICATION");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could Not Click \"Pay By Phone\" Button from Payment Page.");
                WriteLogs("--------" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public UIVillaPlusPaymentInteWindow UIVillaPlusPaymentInteWindow
        {
            get
            {
                if ((this.mUIVillaPlusPaymentInteWindow == null))
                {
                    this.mUIVillaPlusPaymentInteWindow = new UIVillaPlusPaymentInteWindow();
                }
                return this.mUIVillaPlusPaymentInteWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusPaymentInteWindow mUIVillaPlusPaymentInteWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVillaPlusPaymentInteWindow : BrowserWindow
    {
        
        public UIVillaPlusPaymentInteWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Plus | Payment");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPlusPaymentDocument UIVillaPlusPaymentDocument
        {
            get
            {
                if ((this.mUIVillaPlusPaymentDocument == null))
                {
                    this.mUIVillaPlusPaymentDocument = new UIVillaPlusPaymentDocument(this);
                }
                return this.mUIVillaPlusPaymentDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusPaymentDocument mUIVillaPlusPaymentDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVillaPlusPaymentDocument : HtmlDocument
    {
        
        public UIVillaPlusPaymentDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "book";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/booking/", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Plus | Payment");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIBtnRequestBookingCustom
        {
            get
            {
                if ((this.mUIBtnRequestBookingCustom == null))
                {
                    this.mUIBtnRequestBookingCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIBtnRequestBookingCustom.SearchProperties["TagName"] = "A";
                    this.mUIBtnRequestBookingCustom.SearchProperties["Id"] = "btnRequestBooking";
                    this.mUIBtnRequestBookingCustom.FilterProperties["Class"] = "btn bg-green pay-by-phone footer-spacing";
                    this.mUIBtnRequestBookingCustom.FilterProperties["ControlDefinition"] = "class=\"btn bg-green pay-by-phone footer-";
                    this.mUIBtnRequestBookingCustom.WindowTitles.Add("Villa Plus | Payment");
                    #endregion
                }
                return this.mUIBtnRequestBookingCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIBtnRequestBookingCustom;
        #endregion
    }
}
