// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.PaymentPage.clickCancellinkFrm3D_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class clickCancellinkFrm3D_Map
    {
        
        /// <summary>
        /// clickCancellinkFrm3D_Method
        /// </summary>
        public void clickCancellinkFrm3D_Method()
        {
            #region Variable Declarations
            HtmlHyperlink uICancelHyperlink = this.UIMasterCardSecureCodeWindow.UIMasterCardSecureCodeDocument.UICancelHyperlink;
            #endregion

            // Click 'Cancel' link
            Mouse.Click(uICancelHyperlink, new Point(24, 1));
        }
        
        #region Properties
        public UIMasterCardSecureCodeWindow UIMasterCardSecureCodeWindow
        {
            get
            {
                if ((this.mUIMasterCardSecureCodeWindow == null))
                {
                    this.mUIMasterCardSecureCodeWindow = new UIMasterCardSecureCodeWindow();
                }
                return this.mUIMasterCardSecureCodeWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMasterCardSecureCodeWindow mUIMasterCardSecureCodeWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMasterCardSecureCodeWindow : BrowserWindow
    {
        
        public UIMasterCardSecureCodeWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MasterCard® SecureCode™";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MasterCard® SecureCode™");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIMasterCardSecureCodeDocument UIMasterCardSecureCodeDocument
        {
            get
            {
                if ((this.mUIMasterCardSecureCodeDocument == null))
                {
                    this.mUIMasterCardSecureCodeDocument = new UIMasterCardSecureCodeDocument(this);
                }
                return this.mUIMasterCardSecureCodeDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMasterCardSecureCodeDocument mUIMasterCardSecureCodeDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMasterCardSecureCodeDocument : HtmlDocument
    {
        
        public UIMasterCardSecureCodeDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "MasterCard® SecureCode™";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/acs/", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/acs/", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MasterCard® SecureCode™");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UICancelHyperlink
        {
            get
            {
                if ((this.mUICancelHyperlink == null))
                {
                    this.mUICancelHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICancelHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "cancelLink";
                    this.mUICancelHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Cancel";
                    this.mUICancelHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.AbsolutePath, "/acs/", PropertyExpressionOperator.Contains));
                    this.mUICancelHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.Href, "/acs/", PropertyExpressionOperator.Contains));
                    this.mUICancelHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"cancelLink\" href=\"#\"";
                    this.mUICancelHyperlink.WindowTitles.Add("MasterCard® SecureCode™");
                    #endregion
                }
                return this.mUICancelHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUICancelHyperlink;
        #endregion
    }
}
