// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.Footer.clickAtollink_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class clickAtollink_Map:logWriter
    {
        
        /// <summary>
        /// clickAtollink_Method
        /// </summary>
        public void clickAtollink_Method()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIVillaHolidaysThatYouWindow.UIVillaHolidaysThatYouDocument.UIFooterlinksPane.UIItemCustom;
            HtmlImage uIATOLImage = this.UIVillaHolidaysThatYouWindow.UIVillaHolidaysThatYouDocument.UIFooterlinksPane.UIATOLImage;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            //Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover  custom control at (83, 307)
           // Mouse.Hover(uIItemCustom, new Point(83, 307));

            // Reset flag to ensure that play back stops if there is an error.
            //Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'ATOL' image
            Mouse.Click(uIATOLImage, new Point(140, 143));
            string checkurl = uIATOLImage.Href.ToString();
            if (checkurl.Contains("caa"))
            {
                WriteLogs(checkurl + " URL opened Succssefully :Pass");

            }
            else
            {
                WriteLogs(" Search URL NOT opened:Fail ");
            }
            Playback.Wait(1000);
            Keyboard.SendKeys("^W");
        }
        
        #region Properties
        public UIVillaHolidaysThatYouWindow UIVillaHolidaysThatYouWindow
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouWindow == null))
                {
                    this.mUIVillaHolidaysThatYouWindow = new UIVillaHolidaysThatYouWindow();
                }
                return this.mUIVillaHolidaysThatYouWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaHolidaysThatYouWindow mUIVillaHolidaysThatYouWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouWindow : BrowserWindow
    {
        
        public UIVillaHolidaysThatYouWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Villa Holidays That You’ll Love More | Villa Plus";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaHolidaysThatYouDocument UIVillaHolidaysThatYouDocument
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouDocument == null))
                {
                    this.mUIVillaHolidaysThatYouDocument = new UIVillaHolidaysThatYouDocument(this);
                }
                return this.mUIVillaHolidaysThatYouDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaHolidaysThatYouDocument mUIVillaHolidaysThatYouDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouDocument : HtmlDocument
    {
        
        public UIVillaHolidaysThatYouDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Villa Holidays That You’ll Love More | Villa Plus";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://m.villaplus.com/";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public UIFooterlinksPane UIFooterlinksPane
        {
            get
            {
                if ((this.mUIFooterlinksPane == null))
                {
                    this.mUIFooterlinksPane = new UIFooterlinksPane(this);
                }
                return this.mUIFooterlinksPane;
            }
        }
        #endregion
        
        #region Fields
        private UIFooterlinksPane mUIFooterlinksPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFooterlinksPane : HtmlDiv
    {
        
        public UIFooterlinksPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.Id, "footer-links", PropertyExpressionOperator.Contains));
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = "";
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Book with confidence\r\n\r\nYour money is 10";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = "";
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.Class, "bg-blue secure", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.ControlDefinition, "class=\"bg-blue secure\" id=\"footer-links\"", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "27";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "LI";
                    this.mUIItemCustom.FilterProperties["Class"] = null;
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIItemCustom.FilterProperties["InnerText"] = null;
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "3";
                    this.mUIItemCustom.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public HtmlImage UIATOLImage
        {
            get
            {
                if ((this.mUIATOLImage == null))
                {
                    this.mUIATOLImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIATOLImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIATOLImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIATOLImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "ATOL";
                    this.mUIATOLImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.AbsolutePath, "/content/images/atol-logo.svg", PropertyExpressionOperator.Contains));
                    this.mUIATOLImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://m.villaplus.com/content/images/atol-logo.svg";
                    this.mUIATOLImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/default.aspx";
                    this.mUIATOLImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.Href, "http://www.caa.co.uk/default.aspx?catid=27", PropertyExpressionOperator.Contains));
                    this.mUIATOLImage.FilterProperties[HtmlImage.PropertyNames.Class] = "";
                    this.mUIATOLImage.FilterProperties.Add(new PropertyExpression(HtmlImage.PropertyNames.ControlDefinition, "alt=\"ATOL\" src=\"/content/images/atol-log", PropertyExpressionOperator.Contains));
                    this.mUIATOLImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "2";
                    this.mUIATOLImage.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
                    #endregion
                }
                return this.mUIATOLImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        
        private HtmlImage mUIATOLImage;
        #endregion
    }
}
