// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.SearchResultsPage.clickAllusefulLinks_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    using MobileTestAutomation.UIMap.SearchResultsPage.clickUsefulLinksHeading_MapClasses;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class clickAllusefulLinks_Map:logWriter
    {
        
        /// <summary>
        /// clickAllusefulLinks_Method
        /// </summary>
        public void clickAllusefulLinks_Method()
        {
            #region Variable Declarations
            UIPanelfooterCustom UIPanelfooterCustom = this.UIYoursearchfound82VilWindow.UIYoursearchfound82VilDocument.UIPanelfooterCustom;
            HtmlHyperlink uIWhyVillaPlusHyperlink = this.UIYoursearchfound82VilWindow.UIYoursearchfound82VilDocument.UIPanelfooterCustom.UIWhyVillaPlusHyperlink;
            UIYoursearchfound82VilDocument UIYoursearchfound82VilDocument = this.UIYoursearchfound82VilWindow.UIYoursearchfound82VilDocument;
            #endregion
            UITestControlCollection Alllinksnames = uIWhyVillaPlusHyperlink.FindMatchingControls();
            int count = Alllinksnames.Count;
            string Name = string.Empty;
            foreach (HtmlHyperlink LinkName in Alllinksnames)
            {
                try
                {
                    Mouse.Click(LinkName);
                    Name = LinkName.InnerText;
                    WriteLogs("PASS : Clicked \"" + Name + "\" from \"Search Results\" Page.");
                    string URL = UIYoursearchfound82VilDocument.PageUrl;
                    int index = URL.LastIndexOf("/");
                    URL = URL.Substring(index);
                    URL = URL.Replace("-", string.Empty);
                    URL = URL.Replace("/", string.Empty);
                    if (URL.Contains("why"))
                    {
                        Name = "whybookwithus";
                    }
                    if (URL.ToLower()==(Name.Replace(" ", string.Empty).ToLower()))
                    {
                        WriteLogs("PASS : "+URL+" page is opened Successfully On click of \"" + Name + "\" from \"Search Results\" Page.");
                    }
                    else
                    {
                        WriteLogs("FAIL : " + URL + " page is NOT opened On click of \"" + Name + "\" from \"Search Results\" Page.");
                    }
                    this.UIYoursearchfound82VilWindow.Back();
                    WriteLogs("PASS : Clicked \"Back\" button from \"" + Name + "\" Page.");
                    clickUsefulLinksHeading_Map objUsefulLink = new clickUsefulLinksHeading_Map();
                    objUsefulLink.clickUsefulLinksHeading_Method();
                }
                catch (Exception ex)
                {
                    WriteLogs("FAIL : Could not \"" + Name + "\" from \"Search Results\" Page.");
                    WriteLogs("--------" + ex.Message.ToString());
                }
            }
        }
        
        #region Properties
        public UIYoursearchfound82VilWindow UIYoursearchfound82VilWindow
        {
            get
            {
                if ((this.mUIYoursearchfound82VilWindow == null))
                {
                    this.mUIYoursearchfound82VilWindow = new UIYoursearchfound82VilWindow();
                }
                return this.mUIYoursearchfound82VilWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIYoursearchfound82VilWindow mUIYoursearchfound82VilWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIYoursearchfound82VilWindow : BrowserWindow
    {
        
        public UIYoursearchfound82VilWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Your search found", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Your search found 82 Villa holidays;");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIYoursearchfound82VilDocument UIYoursearchfound82VilDocument
        {
            get
            {
                if ((this.mUIYoursearchfound82VilDocument == null))
                {
                    this.mUIYoursearchfound82VilDocument = new UIYoursearchfound82VilDocument(this);
                }
                return this.mUIYoursearchfound82VilDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIYoursearchfound82VilDocument mUIYoursearchfound82VilDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIYoursearchfound82VilDocument : HtmlDocument
    {
        
        public UIYoursearchfound82VilDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Your search found", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "villaplus.com/", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Your search found 82 Villa holidays;");
            #endregion
        }
        
        #region Properties
        public UIPanelfooterCustom UIPanelfooterCustom
        {
            get
            {
                if ((this.mUIPanelfooterCustom == null))
                {
                    this.mUIPanelfooterCustom = new UIPanelfooterCustom(this);
                }
                return this.mUIPanelfooterCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIPanelfooterCustom mUIPanelfooterCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIPanelfooterCustom : HtmlCustom
    {
        
        public UIPanelfooterCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "SECTION";
            this.SearchProperties["Id"] = "panel-footer";
            this.FilterProperties["Class"] = "";
            this.FilterProperties["ControlDefinition"] = "id=\"panel-footer\"";
            this.WindowTitles.Add("Your search found 82 Villa holidays;");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIWhyVillaPlusHyperlink
        {
            get
            {
                if ((this.mUIWhyVillaPlusHyperlink == null))
                {
                    this.mUIWhyVillaPlusHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIWhyVillaPlusHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.AbsolutePath, "/", PropertyExpressionOperator.Contains));
                    this.mUIWhyVillaPlusHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.Href, ".villaplus.com/", PropertyExpressionOperator.Contains));
                    this.mUIWhyVillaPlusHyperlink.WindowTitles.Add("Your search found 82 Villa holidays;");
                    #endregion
                }
                return this.mUIWhyVillaPlusHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIWhyVillaPlusHyperlink;
        #endregion
    }
}
