// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.SearchResultsPage.clickMoreInfoBtn_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class clickMoreInfoBtn_Map:logWriter
    {
        
        /// <summary>
        /// clickMoreInfoBtn_Method
        /// </summary>
        public void clickMoreInfoBtn_Method()
        {
            #region Variable Declarations
            HtmlCustom uISRVillaLink2_1Custom = this.UIYoursearchfound97VilWindow.UIYoursearchfound97VilDocument.UISRVillaLink2_1Custom;
            #endregion
            try
            {
                // Click 'SRVillaLink2_1' custom control
                Mouse.Click(uISRVillaLink2_1Custom, new Point(673, 19));
                WriteLogs("PASS : Clicked \"More Information\" Button successfully.");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could NOT click \"More Information\" Button.");
                WriteLogs("--------" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public UIYoursearchfound97VilWindow UIYoursearchfound97VilWindow
        {
            get
            {
                if ((this.mUIYoursearchfound97VilWindow == null))
                {
                    this.mUIYoursearchfound97VilWindow = new UIYoursearchfound97VilWindow();
                }
                return this.mUIYoursearchfound97VilWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIYoursearchfound97VilWindow mUIYoursearchfound97VilWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIYoursearchfound97VilWindow : BrowserWindow
    {
        
        public UIYoursearchfound97VilWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Your search found", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Your search found 97 Villa holidays;");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIYoursearchfound97VilDocument UIYoursearchfound97VilDocument
        {
            get
            {
                if ((this.mUIYoursearchfound97VilDocument == null))
                {
                    this.mUIYoursearchfound97VilDocument = new UIYoursearchfound97VilDocument(this);
                }
                return this.mUIYoursearchfound97VilDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIYoursearchfound97VilDocument mUIYoursearchfound97VilDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIYoursearchfound97VilDocument : HtmlDocument
    {
        
        public UIYoursearchfound97VilDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Your search found", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/search/searchresult", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/search/searchresult", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Your search found 97 Villa holidays;");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UISRVillaLink2_1Custom
        {
            get
            {
                if ((this.mUISRVillaLink2_1Custom == null))
                {
                    this.mUISRVillaLink2_1Custom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUISRVillaLink2_1Custom.SearchProperties["TagName"] = "A";
                    this.mUISRVillaLink2_1Custom.SearchProperties.Add(new PropertyExpression("Id", "SRVillaLink2_", PropertyExpressionOperator.Contains));
                    this.mUISRVillaLink2_1Custom.FilterProperties["Class"] = "btn bg-blue MousePointer";
                    this.mUISRVillaLink2_1Custom.FilterProperties["ControlDefinition"] = "class=\"btn bg-blue MousePointer\" id=\"SRV";
                    this.mUISRVillaLink2_1Custom.WindowTitles.Add("Your search found 97 Villa holidays;");
                    #endregion
                }
                return this.mUISRVillaLink2_1Custom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUISRVillaLink2_1Custom;
        #endregion
    }
}
