// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.SearchResultsPage.clickClearFilter_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class clickClearFilter_Map
    {
        
        /// <summary>
        /// clickClearFilter_Method
        /// </summary>
        public void clickClearFilter_Method()
        {
            #region Variable Declarations
            HtmlHyperlink uIClearFiltersHyperlink = this.UIYoursearchfound18VilWindow.UIYoursearchfound18VilDocument.UIClearFiltersHyperlink;
            #endregion

            // Click 'Clear Filters' link
            Mouse.Click(uIClearFiltersHyperlink, new Point(354, 24));
        }
        
        #region Properties
        public UIYoursearchfound18VilWindow UIYoursearchfound18VilWindow
        {
            get
            {
                if ((this.mUIYoursearchfound18VilWindow == null))
                {
                    this.mUIYoursearchfound18VilWindow = new UIYoursearchfound18VilWindow();
                }
                return this.mUIYoursearchfound18VilWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIYoursearchfound18VilWindow mUIYoursearchfound18VilWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIYoursearchfound18VilWindow : BrowserWindow
    {
        
        public UIYoursearchfound18VilWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Your search found", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Your search found 18 Villa holidays");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIYoursearchfound18VilDocument UIYoursearchfound18VilDocument
        {
            get
            {
                if ((this.mUIYoursearchfound18VilDocument == null))
                {
                    this.mUIYoursearchfound18VilDocument = new UIYoursearchfound18VilDocument(this);
                }
                return this.mUIYoursearchfound18VilDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIYoursearchfound18VilDocument mUIYoursearchfound18VilDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIYoursearchfound18VilDocument : HtmlDocument
    {
        
        public UIYoursearchfound18VilDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Your search found", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/search/searchresult", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/search/searchresult", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Your search found 18 Villa holidays");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIClearFiltersHyperlink
        {
            get
            {
                if ((this.mUIClearFiltersHyperlink == null))
                {
                    this.mUIClearFiltersHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIClearFiltersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "btnClearFilters";
                    this.mUIClearFiltersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Clear Filters";
                    this.mUIClearFiltersHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.AbsolutePath, "/search/searchresult", PropertyExpressionOperator.Contains));
                    this.mUIClearFiltersHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.Href, ".villaplus.com/search/searchresult#", PropertyExpressionOperator.Contains));
                    this.mUIClearFiltersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn bg-orange";
                    this.mUIClearFiltersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn bg-orange\" id=\"btnClearFilter";
                    this.mUIClearFiltersHyperlink.WindowTitles.Add("Your search found 18 Villa holidays");
                    #endregion
                }
                return this.mUIClearFiltersHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIClearFiltersHyperlink;
        #endregion
    }
}
