// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.SearchResultsPage.selectSortOption_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    using MobileTestAutomation.UIMap.SearchResultsPage.clickApplySort_MapClasses;
    using MobileTestAutomation.UIMap.SearchResultsPage.clickSortBy_MapClasses;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class selectSortOption_Map:logWriter
    {
        
        /// <summary>
        /// selectSortOption_Method - Use 'selectSortOption_MethodParams' to pass parameters into this method.
        /// </summary>
        public void selectSortOption_Method()
        {
            #region Variable Declarations
            HtmlRadioButton uIPricehightolowRadioButton = this.UIYoursearchfound18VilWindow.UIYoursearchfound18VilDocument.UIPricehightolowRadioButton;
            #endregion
            string selectedSortOption = string.Empty;
            clickApplySort_Map ObjApplyFilterBtn = new clickApplySort_Map();
            clickSortBy_Map ObjClickSortBy = new clickSortBy_Map();

            try
            {
                // Select 'Price high to low' radio button
                //uIPricehightolowRadioButton.Selected = this.selectSortOption_MethodParams.UIPricehightolowRadioButtonSelected;
                UITestControlCollection ui = uIPricehightolowRadioButton.FindMatchingControls();
                int count = ui.Count;
                foreach (HtmlRadioButton eachSortOption in ui)
                //for (int i = initTagInstance; i < count; i++)
                {
                    Mouse.Click(eachSortOption);
                    selectedSortOption = eachSortOption.LabeledBy;
                    WriteLogs("PASS : Selected \"" + selectedSortOption + "\" Option from \"Search Results\" Page.");
                    ObjApplyFilterBtn.clickApplySort_Method();
                    ObjClickSortBy.clickSortBy_Method();
                }
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could NOT select \"" + selectedSortOption + "\" Option from \"Search Results\" Page. " + ex.Message);
            }
        }
        
        #region Properties
        public virtual selectSortOption_MethodParams selectSortOption_MethodParams
        {
            get
            {
                if ((this.mselectSortOption_MethodParams == null))
                {
                    this.mselectSortOption_MethodParams = new selectSortOption_MethodParams();
                }
                return this.mselectSortOption_MethodParams;
            }
        }
        
        public UIYoursearchfound18VilWindow UIYoursearchfound18VilWindow
        {
            get
            {
                if ((this.mUIYoursearchfound18VilWindow == null))
                {
                    this.mUIYoursearchfound18VilWindow = new UIYoursearchfound18VilWindow();
                }
                return this.mUIYoursearchfound18VilWindow;
            }
        }
        #endregion
        
        #region Fields
        private selectSortOption_MethodParams mselectSortOption_MethodParams;
        
        private UIYoursearchfound18VilWindow mUIYoursearchfound18VilWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'selectSortOption_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class selectSortOption_MethodParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Price high to low' radio button
        /// </summary>
        public bool UIPricehightolowRadioButtonSelected = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIYoursearchfound18VilWindow : BrowserWindow
    {
        
        public UIYoursearchfound18VilWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Your search found", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Your search found 18 Villa holidays");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIYoursearchfound18VilDocument UIYoursearchfound18VilDocument
        {
            get
            {
                if ((this.mUIYoursearchfound18VilDocument == null))
                {
                    this.mUIYoursearchfound18VilDocument = new UIYoursearchfound18VilDocument(this);
                }
                return this.mUIYoursearchfound18VilDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIYoursearchfound18VilDocument mUIYoursearchfound18VilDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIYoursearchfound18VilDocument : HtmlDocument
    {
        
        public UIYoursearchfound18VilDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Your search found", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/search/searchresult", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/search/searchresult", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Your search found 18 Villa holidays");
            #endregion
        }
        
        #region Properties
        public HtmlRadioButton UIPricehightolowRadioButton
        {
            get
            {
                if ((this.mUIPricehightolowRadioButton == null))
                {
                    this.mUIPricehightolowRadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIPricehightolowRadioButton.SearchProperties.Add(new PropertyExpression(HtmlRadioButton.PropertyNames.Id, "sortradiooption-", PropertyExpressionOperator.Contains));
                    this.mUIPricehightolowRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "radio-sort";
                    this.mUIPricehightolowRadioButton.FilterProperties.Add(new PropertyExpression(HtmlRadioButton.PropertyNames.ControlDefinition, "name=\"radio-sort\"", PropertyExpressionOperator.Contains));
                    this.mUIPricehightolowRadioButton.WindowTitles.Add("Your search found 18 Villa holidays");
                    #endregion
                }
                return this.mUIPricehightolowRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlRadioButton mUIPricehightolowRadioButton;
        #endregion
    }
}
