// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.SearchResultsPage.verifyProductPagedisplay_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class verifyProductPagedisplay_Map:logWriter
    {
        
        /// <summary>
        /// verifyProductPagedisplay_Method - Use 'verifyProductPagedisplay_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void verifyProductPagedisplay_Method(string VillaNAME, string strURL)
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIVillaVerdialesInFrigWindow.UIVillaVerdialesInFrigDocument.UIDvProductPane.UIItemCustom;
            #endregion

            delayExecution(strURL);

            string ExpVillaName = VillaNAME;
            string ActVillaName = uIItemCustom.InnerText;
            int index = uIItemCustom.InnerText.IndexOf("\r\n");
            ActVillaName = ActVillaName.Substring(0, index);
            try
            {
                StringAssert.Contains(ActVillaName, ExpVillaName);
                WriteLogs("PASS : Product Page is opened successfully for \"" + VillaNAME + "\".");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Product Page is NOT opened for \"" + VillaNAME + "\".");
                WriteLogs("--------" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public virtual verifyProductPagedisplay_MethodExpectedValues verifyProductPagedisplay_MethodExpectedValues
        {
            get
            {
                if ((this.mverifyProductPagedisplay_MethodExpectedValues == null))
                {
                    this.mverifyProductPagedisplay_MethodExpectedValues = new verifyProductPagedisplay_MethodExpectedValues();
                }
                return this.mverifyProductPagedisplay_MethodExpectedValues;
            }
        }
        
        public UIVillaVerdialesInFrigWindow UIVillaVerdialesInFrigWindow
        {
            get
            {
                if ((this.mUIVillaVerdialesInFrigWindow == null))
                {
                    this.mUIVillaVerdialesInFrigWindow = new UIVillaVerdialesInFrigWindow();
                }
                return this.mUIVillaVerdialesInFrigWindow;
            }
        }
        #endregion
        
        #region Fields
        private verifyProductPagedisplay_MethodExpectedValues mverifyProductPagedisplay_MethodExpectedValues;
        
        private UIVillaVerdialesInFrigWindow mUIVillaVerdialesInFrigWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'verifyProductPagedisplay_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class verifyProductPagedisplay_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of custom control contains 'Villa Verdiales, Frigiliana, Costa del Sol'
        /// </summary>
        public string UIItemCustomInnerText = "Villa Verdiales, Frigiliana, Costa del Sol";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaVerdialesInFrigWindow : BrowserWindow
    {
        
        public UIVillaVerdialesInFrigWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "| Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Verdiales In Frigiliana, Costa del Sol | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaVerdialesInFrigDocument UIVillaVerdialesInFrigDocument
        {
            get
            {
                if ((this.mUIVillaVerdialesInFrigDocument == null))
                {
                    this.mUIVillaVerdialesInFrigDocument = new UIVillaVerdialesInFrigDocument(this);
                }
                return this.mUIVillaVerdialesInFrigDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaVerdialesInFrigDocument mUIVillaVerdialesInFrigDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaVerdialesInFrigDocument : HtmlDocument
    {
        
        public UIVillaVerdialesInFrigDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "| Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/villas/", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/villas/", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Verdiales In Frigiliana, Costa del Sol | Villa Plus");
            #endregion
        }
        
        #region Properties
        public UIDvProductPane UIDvProductPane
        {
            get
            {
                if ((this.mUIDvProductPane == null))
                {
                    this.mUIDvProductPane = new UIDvProductPane(this);
                }
                return this.mUIDvProductPane;
            }
        }
        #endregion
        
        #region Fields
        private UIDvProductPane mUIDvProductPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIDvProductPane : HtmlDiv
    {
        
        public UIDvProductPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "dvProduct";
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.InnerText, "Villa", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"dvProduct\"";
            this.WindowTitles.Add("Villa Verdiales In Frigiliana, Costa del Sol | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "SECTION";
                    this.mUIItemCustom.FilterProperties["Class"] = "villa-description";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "class=\"villa-description\"";
                    this.mUIItemCustom.WindowTitles.Add("Villa Verdiales In Frigiliana, Costa del Sol | Villa Plus");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        #endregion
    }
}
