// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.SearchResultsPage.verifyVillaName_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class verifyVillaName_Map
    {
        
        /// <summary>
        /// verifyVillaName_Method - Use 'verifyVillaName_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public string verifyVillaName_Method()
        {
            #region Variable Declarations
            HtmlCustom uISRVillaLink1_1Custom = this.UIYoursearchfound8VillWindow.UIYoursearchfound8VillDocument.UISRVillaLink1_1Custom;
            #endregion

            // Verify that the 'InnerText' property of 'SRVillaLink1_1' custom control contains 'Villa St George'
            //StringAssert.Contains(uISRVillaLink1_1Custom.InnerText, this.verifyVillaName_MethodExpectedValues.UISRVillaLink1_1CustomInnerText);
            string VillaName = uISRVillaLink1_1Custom.InnerText.ToString();
            return VillaName;

        }
        
        #region Properties
        public virtual verifyVillaName_MethodExpectedValues verifyVillaName_MethodExpectedValues
        {
            get
            {
                if ((this.mverifyVillaName_MethodExpectedValues == null))
                {
                    this.mverifyVillaName_MethodExpectedValues = new verifyVillaName_MethodExpectedValues();
                }
                return this.mverifyVillaName_MethodExpectedValues;
            }
        }
        
        public UIYoursearchfound8VillWindow UIYoursearchfound8VillWindow
        {
            get
            {
                if ((this.mUIYoursearchfound8VillWindow == null))
                {
                    this.mUIYoursearchfound8VillWindow = new UIYoursearchfound8VillWindow();
                }
                return this.mUIYoursearchfound8VillWindow;
            }
        }
        #endregion
        
        #region Fields
        private verifyVillaName_MethodExpectedValues mverifyVillaName_MethodExpectedValues;
        
        private UIYoursearchfound8VillWindow mUIYoursearchfound8VillWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'verifyVillaName_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class verifyVillaName_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'SRVillaLink1_1' custom control contains 'Villa St George'
        /// </summary>
        public string UISRVillaLink1_1CustomInnerText = "Villa St George";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIYoursearchfound8VillWindow : BrowserWindow
    {
        
        public UIYoursearchfound8VillWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIYoursearchfound8VillDocument UIYoursearchfound8VillDocument
        {
            get
            {
                if ((this.mUIYoursearchfound8VillDocument == null))
                {
                    this.mUIYoursearchfound8VillDocument = new UIYoursearchfound8VillDocument(this);
                }
                return this.mUIYoursearchfound8VillDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIYoursearchfound8VillDocument mUIYoursearchfound8VillDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIYoursearchfound8VillDocument : HtmlDocument
    {
        
        public UIYoursearchfound8VillDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/search/searchResult", PropertyExpressionOperator.Contains));
            #endregion
        }
        
        #region Properties
        public HtmlCustom UISRVillaLink1_1Custom
        {
            get
            {
                if ((this.mUISRVillaLink1_1Custom == null))
                {
                    this.mUISRVillaLink1_1Custom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUISRVillaLink1_1Custom.SearchProperties["TagName"] = "A";
                    this.mUISRVillaLink1_1Custom.SearchProperties.Add(new PropertyExpression("Id", "SRVillaLink1_1", PropertyExpressionOperator.Contains));
                    this.mUISRVillaLink1_1Custom.FilterProperties.Add(new PropertyExpression("Class", "text-orange MousePointer", PropertyExpressionOperator.Contains));
                    this.mUISRVillaLink1_1Custom.FilterProperties.Add(new PropertyExpression("ControlDefinition", "class=\"text-orange MousePointer\"", PropertyExpressionOperator.Contains));
                    #endregion
                }
                return this.mUISRVillaLink1_1Custom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUISRVillaLink1_1Custom;
        #endregion
    }
}
