// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.ExtrasPage.clickContinueFrmExtrasPage_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class clickContinueFrmExtrasPage_Map :logWriter
    {
        
        /// <summary>
        /// clickContinueFrmExtrasPage_Method
        /// </summary>
        public void clickContinueFrmExtrasPage_Method()
        {
            #region Variable Declarations
            HtmlHyperlink uIContinueHyperlink = this.UIHolidayExtrasVillaPlWindow.UIHolidayExtrasVillaPlDocument.UIContinueHyperlink;
            #endregion
            Keyboard.SendKeys("{PGDN}");
            try
            {
                uIContinueHyperlink.SetFocus();
                Mouse.Click(uIContinueHyperlink, new Point(709, 20));
                WriteLogs("PASS : Clicked Continue Button from Extras Page. : VERIFICATION");
            }
            catch
            {

            }
        }
        
        #region Properties
        public UIHolidayExtrasVillaPlWindow UIHolidayExtrasVillaPlWindow
        {
            get
            {
                if ((this.mUIHolidayExtrasVillaPlWindow == null))
                {
                    this.mUIHolidayExtrasVillaPlWindow = new UIHolidayExtrasVillaPlWindow();
                }
                return this.mUIHolidayExtrasVillaPlWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIHolidayExtrasVillaPlWindow mUIHolidayExtrasVillaPlWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHolidayExtrasVillaPlWindow : BrowserWindow
    {
        
        public UIHolidayExtrasVillaPlWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Holiday Extras | Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Holiday Extras | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHolidayExtrasVillaPlDocument UIHolidayExtrasVillaPlDocument
        {
            get
            {
                if ((this.mUIHolidayExtrasVillaPlDocument == null))
                {
                    this.mUIHolidayExtrasVillaPlDocument = new UIHolidayExtrasVillaPlDocument(this);
                }
                return this.mUIHolidayExtrasVillaPlDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHolidayExtrasVillaPlDocument mUIHolidayExtrasVillaPlDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHolidayExtrasVillaPlDocument : HtmlDocument
    {
        
        public UIHolidayExtrasVillaPlDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "book";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Holiday Extras | Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/Extras/ShowExtras", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/booking/Extras/ShowExtras", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Holiday Extras | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIContinueHyperlink
        {
            get
            {
                if ((this.mUIContinueHyperlink == null))
                {
                    this.mUIContinueHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIContinueHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "btnContinue";
                    this.mUIContinueHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Continue";
                    this.mUIContinueHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "Continue();";
                    this.mUIContinueHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:Continue();";
                    this.mUIContinueHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn bg-green footer-spacing";
                    this.mUIContinueHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn bg-green footer-spacing\" id=\"";
                    this.mUIContinueHyperlink.WindowTitles.Add("Holiday Extras | Villa Plus");
                    #endregion
                }
                return this.mUIContinueHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIContinueHyperlink;
        #endregion
    }
}
