// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.ExtrasPage.clickAddCarHireButton_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    using MobileTestAutomation.UIMap.ExtrasPage.moveScrollPage_MapClasses;
    using MobileTestAutomation.UIMap.ExtrasPage.scrollMouseForCarSection_MapClasses;



    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class clickAddCarHireButton_Map : logWriter
    {

        /// <summary>
        /// clickAddCarHireButton_Method
        /// </summary>
        public void clickAddCarHireButton_Method()
        {
            #region Variable Declarations
            HtmlCustom uIAddCarCustom = this.UIHolidayExtrasVillaPlWindow.UIHolidayExtrasVillaPlDocument.UIAddCarCustom;
            #endregion
            moveScrollPage_Map ScrollPage = new moveScrollPage_Map();
            scrollMouseForCarSection_Map scrollExtrasPageselectAgain = new scrollMouseForCarSection_Map();

            HtmlDocument findCarBu = new HtmlDocument(this.mUIHolidayExtrasVillaPlWindow);
            HtmlCustom ClickAddCar = new HtmlCustom(findCarBu);
            ScrollPage.moveScrollExtrasPage_Method();
            ClickAddCar.SearchProperties[HtmlCustom.PropertyNames.Id] = "addCar";
            try
            {
                // Click 'addCar' custom control   
                Mouse.Click(ClickAddCar);
                WriteLogs("PASS : Clicked on the Add Car Hire Button. : VERIFICATION");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could Not Click on the Add Car Hire Button ");
                WriteLogs("----"+ ex.Message.ToString());

            }
            //System.Threading.Thread.Sleep(1000);

            //Clicking on the Remove Button
            HtmlDiv removeButton1 = new HtmlDiv(findCarBu);
            removeButton1.SearchProperties[HtmlDiv.PropertyNames.Id] = "rmvcar1";
            try
            {
                Mouse.Click(removeButton1);
                WriteLogs("PASS : Clicked on the Removed Car Hire  Button.");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could Not Click on the Additional Car Hire  Button ");
                WriteLogs("----" + ex.Message.ToString());
            }

            // Clicking on the confirm Car Button
            HtmlCustom ConfirmCarButton = new HtmlCustom(findCarBu);
            ConfirmCarButton.SearchProperties[HtmlCustom.PropertyNames.Id] = "confirmCar";
            try
            {
                Mouse.Click(ConfirmCarButton);
                WriteLogs("PASS : Clicked on the Confirm Car Hire Button. : VERIFICATION");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could Not Click on the Confirm Car Hire Button ");
                WriteLogs("----" + ex.Message.ToString());
            }

            // Again Clicking on the confirm Car Button
            System.Threading.Thread.Sleep(200);
            HtmlCustom ClickAddCar1 = new HtmlCustom(findCarBu);
            scrollExtrasPageselectAgain.scrollMouseForCarSection_Method();
            ClickAddCar1.SearchProperties[HtmlCustom.PropertyNames.Id] = "addCar";
            try
            {
                Mouse.Click(ClickAddCar1);
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could Not Click the Add Car Hire Button.");
                WriteLogs("----" + ex.Message.ToString());
            }
        }




        #region Properties
        public UIHolidayExtrasVillaPlWindow UIHolidayExtrasVillaPlWindow
        {
            get
            {
                if ((this.mUIHolidayExtrasVillaPlWindow == null))
                {
                    this.mUIHolidayExtrasVillaPlWindow = new UIHolidayExtrasVillaPlWindow();
                }
                return this.mUIHolidayExtrasVillaPlWindow;
            }
        }
        #endregion

        #region Fields
        private UIHolidayExtrasVillaPlWindow mUIHolidayExtrasVillaPlWindow;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHolidayExtrasVillaPlWindow : BrowserWindow
    {

        public UIHolidayExtrasVillaPlWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Holiday Extras | Villa Plus";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Holiday Extras | Villa Plus");
            #endregion
        }

        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }

        #region Properties
        public UIHolidayExtrasVillaPlDocument UIHolidayExtrasVillaPlDocument
        {
            get
            {
                if ((this.mUIHolidayExtrasVillaPlDocument == null))
                {
                    this.mUIHolidayExtrasVillaPlDocument = new UIHolidayExtrasVillaPlDocument(this);
                }
                return this.mUIHolidayExtrasVillaPlDocument;
            }
        }
        #endregion

        #region Fields
        private UIHolidayExtrasVillaPlDocument mUIHolidayExtrasVillaPlDocument;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHolidayExtrasVillaPlDocument : HtmlDocument
    {

        public UIHolidayExtrasVillaPlDocument(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "book";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Holiday Extras | Villa Plus";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/Extras/ShowExtras", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Holiday Extras | Villa Plus");
            #endregion
        }

        #region Properties
        public HtmlCustom UIAddCarCustom
        {
            get
            {
                if ((this.mUIAddCarCustom == null))
                {
                    this.mUIAddCarCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIAddCarCustom.SearchProperties.Add(new PropertyExpression("Id", "addCar", PropertyExpressionOperator.Contains));
                    this.mUIAddCarCustom.FilterProperties.Add(new PropertyExpression("Class", "btn bg-orange MousePointer", PropertyExpressionOperator.Contains));
                    this.mUIAddCarCustom.FilterProperties.Add(new PropertyExpression("ControlDefinition", "class=\"btn bg-orange MousePointer\"", PropertyExpressionOperator.Contains));
                    this.mUIAddCarCustom.WindowTitles.Add("Holiday Extras | Villa Plus");
                    #endregion
                }
                return this.mUIAddCarCustom;
            }
        }
        #endregion

        #region Fields
        private HtmlCustom mUIAddCarCustom;
        #endregion
    }
}
