// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.ExtrasPage.clickLaterBtn_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class clickLaterBtn_Map:logWriter
    {
        public void clickLaterBtn_Method()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIVillaPlusCustomerFliWindow.UIVillaPlusCustomerFliDocument.UIFrmSaveCustFlightCustom.UIItemCustom;
            #endregion
            try
            {
                Mouse.Click(uIItemCustom);
                WriteLogs("PASS : Clicked \"Later\" Button From \"Your Flight\" Page.");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could Not Click \"Later\" Button From \"Your Flight\" Page. ");
                WriteLogs("----" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public UIVillaPlusCustomerFliWindow UIVillaPlusCustomerFliWindow
        {
            get
            {
                if ((this.mUIVillaPlusCustomerFliWindow == null))
                {
                    this.mUIVillaPlusCustomerFliWindow = new UIVillaPlusCustomerFliWindow();
                }
                return this.mUIVillaPlusCustomerFliWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusCustomerFliWindow mUIVillaPlusCustomerFliWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVillaPlusCustomerFliWindow : BrowserWindow
    {
        
        public UIVillaPlusCustomerFliWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Plus | Customer Flight Info");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPlusCustomerFliDocument UIVillaPlusCustomerFliDocument
        {
            get
            {
                if ((this.mUIVillaPlusCustomerFliDocument == null))
                {
                    this.mUIVillaPlusCustomerFliDocument = new UIVillaPlusCustomerFliDocument(this);
                }
                return this.mUIVillaPlusCustomerFliDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusCustomerFliDocument mUIVillaPlusCustomerFliDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVillaPlusCustomerFliDocument : HtmlDocument
    {
        
        public UIVillaPlusCustomerFliDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "book";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/customer-flight-info", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/customer-flight-info", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Plus | Customer Flight Info");
            #endregion
        }
        
        #region Properties
        public UIFrmSaveCustFlightCustom UIFrmSaveCustFlightCustom
        {
            get
            {
                if ((this.mUIFrmSaveCustFlightCustom == null))
                {
                    this.mUIFrmSaveCustFlightCustom = new UIFrmSaveCustFlightCustom(this);
                }
                return this.mUIFrmSaveCustFlightCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIFrmSaveCustFlightCustom mUIFrmSaveCustFlightCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFrmSaveCustFlightCustom : HtmlCustom
    {
        
        public UIFrmSaveCustFlightCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "frmSaveCustFlight";
            this.FilterProperties["ControlDefinition"] = "id=\"frmSaveCustFlight\" action=\"\" method=";
            this.WindowTitles.Add("Villa Plus | Customer Flight Info");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "A";
                    this.mUIItemCustom.FilterProperties["Class"] = "btn bg-orange";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "class=\"btn bg-orange\" onclick=\"SubmitPag";
                    this.mUIItemCustom.WindowTitles.Add("Villa Plus | Customer Flight Info");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        #endregion
    }
}
