// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.ExtrasPage.moveScrollPage_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class moveScrollPage_Map
    {
        
        /// <summary>
        /// moveScrollPage_Method - Use 'moveScrollPage_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void moveScrollExtrasPage_Method()
        {
            #region Variable Declarations
            HtmlScrollBar uIItemScrollBar = this.UIHolidayExtrasVillaPlWindow.UIHolidayExtrasVillaPlDocument.UIItemScrollBar;
            #endregion

            if (uIItemScrollBar.Exists)
            {

                Mouse.Click(uIItemScrollBar);
                Mouse.MoveScrollWheel(-6); 
            }

            // Verify that the 'Exists' property of scroll bar equals 'True'
            //Assert.AreEqual(this.moveScrollPage_MethodExpectedValues.UIItemScrollBarExists, uIItemScrollBar.Exists);
        }
        
        #region Properties
        public virtual moveScrollPage_MethodExpectedValues moveScrollPage_MethodExpectedValues
        {
            get
            {
                if ((this.mmoveScrollPage_MethodExpectedValues == null))
                {
                    this.mmoveScrollPage_MethodExpectedValues = new moveScrollPage_MethodExpectedValues();
                }
                return this.mmoveScrollPage_MethodExpectedValues;
            }
        }
        
        public UIHolidayExtrasVillaPlWindow UIHolidayExtrasVillaPlWindow
        {
            get
            {
                if ((this.mUIHolidayExtrasVillaPlWindow == null))
                {
                    this.mUIHolidayExtrasVillaPlWindow = new UIHolidayExtrasVillaPlWindow();
                }
                return this.mUIHolidayExtrasVillaPlWindow;
            }
        }
        #endregion
        
        #region Fields
        private moveScrollPage_MethodExpectedValues mmoveScrollPage_MethodExpectedValues;
        
        private UIHolidayExtrasVillaPlWindow mUIHolidayExtrasVillaPlWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'moveScrollPage_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class moveScrollPage_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Exists' property of scroll bar equals 'True'
        /// </summary>
        public bool UIItemScrollBarExists = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHolidayExtrasVillaPlWindow : BrowserWindow
    {
        
        public UIHolidayExtrasVillaPlWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Holiday Extras | Villa Plus";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Holiday Extras | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHolidayExtrasVillaPlDocument UIHolidayExtrasVillaPlDocument
        {
            get
            {
                if ((this.mUIHolidayExtrasVillaPlDocument == null))
                {
                    this.mUIHolidayExtrasVillaPlDocument = new UIHolidayExtrasVillaPlDocument(this);
                }
                return this.mUIHolidayExtrasVillaPlDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHolidayExtrasVillaPlDocument mUIHolidayExtrasVillaPlDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHolidayExtrasVillaPlDocument : HtmlDocument
    {
        
        public UIHolidayExtrasVillaPlDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "book";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Holiday Extras | Villa Plus";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/Extras/ShowExtras", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Holiday Extras | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlScrollBar UIItemScrollBar
        {
            get
            {
                if ((this.mUIItemScrollBar == null))
                {
                    this.mUIItemScrollBar = new HtmlScrollBar(this);
                    #region Search Criteria
                    this.mUIItemScrollBar.SearchProperties[HtmlScrollBar.PropertyNames.Orientation] = "Vertical";
                    this.mUIItemScrollBar.WindowTitles.Add("Holiday Extras | Villa Plus");
                    #endregion
                }
                return this.mUIItemScrollBar;
            }
        }
        #endregion
        
        #region Fields
        private HtmlScrollBar mUIItemScrollBar;
        #endregion
    }
}
