// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.ExtrasPage.verifyVillaExtras_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class verifyVillaExtras_Map
    {
        
        /// <summary>
        /// verifyVillaExtras_Method - Use 'verifyVillaExtras_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void verifyVillaExtras_Method()
        {
            #region Variable Declarations
            HtmlDiv uIItem0xStarterPack000Pane = this.UIHolidayExtrasVillaPlWindow.UIHolidayExtrasVillaPlDocument.UIItem0xStarterPack000Pane;
            #endregion



            // Verify that the 'InnerText' property of '- 0 x Starter Pack - £0.00 +' pane equals '- 
            //0 x Starter Pack - £0.00
            //+ '
            Assert.AreEqual(this.verifyVillaExtras_MethodExpectedValues.UIItem0xStarterPack000PaneInnerText, uIItem0xStarterPack000Pane.InnerText);
        }
        
        #region Properties
        public virtual verifyVillaExtras_MethodExpectedValues verifyVillaExtras_MethodExpectedValues
        {
            get
            {
                if ((this.mverifyVillaExtras_MethodExpectedValues == null))
                {
                    this.mverifyVillaExtras_MethodExpectedValues = new verifyVillaExtras_MethodExpectedValues();
                }
                return this.mverifyVillaExtras_MethodExpectedValues;
            }
        }
        
        public UIHolidayExtrasVillaPlWindow UIHolidayExtrasVillaPlWindow
        {
            get
            {
                if ((this.mUIHolidayExtrasVillaPlWindow == null))
                {
                    this.mUIHolidayExtrasVillaPlWindow = new UIHolidayExtrasVillaPlWindow();
                }
                return this.mUIHolidayExtrasVillaPlWindow;
            }
        }
        #endregion
        
        #region Fields
        private verifyVillaExtras_MethodExpectedValues mverifyVillaExtras_MethodExpectedValues;
        
        private UIHolidayExtrasVillaPlWindow mUIHolidayExtrasVillaPlWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'verifyVillaExtras_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class verifyVillaExtras_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of '- 0 x Starter Pack - £0.00 +' pane equals '- 
        ///0 x Starter Pack - £0.00
        ///+ '
        /// </summary>
        public string UIItem0xStarterPack000PaneInnerText = "- \r\n0 x Starter Pack - £0.00\r\n+ ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHolidayExtrasVillaPlWindow : BrowserWindow
    {
        
        public UIHolidayExtrasVillaPlWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Holiday Extras | Villa Plus";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Holiday Extras | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHolidayExtrasVillaPlDocument UIHolidayExtrasVillaPlDocument
        {
            get
            {
                if ((this.mUIHolidayExtrasVillaPlDocument == null))
                {
                    this.mUIHolidayExtrasVillaPlDocument = new UIHolidayExtrasVillaPlDocument(this);
                }
                return this.mUIHolidayExtrasVillaPlDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHolidayExtrasVillaPlDocument mUIHolidayExtrasVillaPlDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHolidayExtrasVillaPlDocument : HtmlDocument
    {
        
        public UIHolidayExtrasVillaPlDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "book";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Holiday Extras | Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/Extras/ShowExtras", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/booking/Extras/ShowExtras", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Holiday Extras | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItem0xStarterPack000Pane
        {
            get
            {
                if ((this.mUIItem0xStarterPack000Pane == null))
                {
                    this.mUIItem0xStarterPack000Pane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItem0xStarterPack000Pane.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.InnerText, "- \r\n0 x Starter Pack - £0.00\r\n+ ", PropertyExpressionOperator.Contains));
                    this.mUIItem0xStarterPack000Pane.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.Class, "minus-plus min vExtras", PropertyExpressionOperator.Contains));
                    this.mUIItem0xStarterPack000Pane.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.ControlDefinition, "class=\"minus-plus min vExtras\" ", PropertyExpressionOperator.Contains));
                    this.mUIItem0xStarterPack000Pane.WindowTitles.Add("Holiday Extras | Villa Plus");
                    #endregion
                }
                return this.mUIItem0xStarterPack000Pane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItem0xStarterPack000Pane;
        #endregion
    }
}
