// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.LeadPaxPage.clickLookupAddressBtn_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class clickLookupAddressBtn_Map:logWriter
    {
        public void clickLookupAddressBtn_Method()
        {
            #region Variable Declarations
            HtmlHyperlink uILookUpAddressHyperlink = this.UIVillaPlusLeadPassengWindow.UIVillaPlusLeadPassengDocument.UILookUpAddressHyperlink;
            #endregion
            try
            {
                Mouse.Click(uILookUpAddressHyperlink, new Point(367, 22));
                WriteLogs("PASS : Clicked \"Look Up Address\" Button.");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could NOT Click \"Look Up Address\" Button.");
                WriteLogs("--------" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public UIVillaPlusLeadPassengWindow UIVillaPlusLeadPassengWindow
        {
            get
            {
                if ((this.mUIVillaPlusLeadPassengWindow == null))
                {
                    this.mUIVillaPlusLeadPassengWindow = new UIVillaPlusLeadPassengWindow();
                }
                return this.mUIVillaPlusLeadPassengWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusLeadPassengWindow mUIVillaPlusLeadPassengWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaPlusLeadPassengWindow : BrowserWindow
    {
        
        public UIVillaPlusLeadPassengWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Plus | Lead Passenger");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPlusLeadPassengDocument UIVillaPlusLeadPassengDocument
        {
            get
            {
                if ((this.mUIVillaPlusLeadPassengDocument == null))
                {
                    this.mUIVillaPlusLeadPassengDocument = new UIVillaPlusLeadPassengDocument(this);
                }
                return this.mUIVillaPlusLeadPassengDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusLeadPassengDocument mUIVillaPlusLeadPassengDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaPlusLeadPassengDocument : HtmlDocument
    {
        
        public UIVillaPlusLeadPassengDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "book";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/lead-passenger", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/booking/lead-passenger", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Plus | Lead Passenger");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UILookUpAddressHyperlink
        {
            get
            {
                if ((this.mUILookUpAddressHyperlink == null))
                {
                    this.mUILookUpAddressHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILookUpAddressHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "anchrPostCode";
                    this.mUILookUpAddressHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Look-Up Address";
                    this.mUILookUpAddressHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/booking/lead-passenger";
                    this.mUILookUpAddressHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.Href, ".villaplus.com/booking/lead-passenger", PropertyExpressionOperator.Contains));
                    this.mUILookUpAddressHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn bg-orange showClass";
                    this.mUILookUpAddressHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn bg-orange showClass\" id=\"anch";
                    this.mUILookUpAddressHyperlink.WindowTitles.Add("Villa Plus | Lead Passenger");
                    #endregion
                }
                return this.mUILookUpAddressHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUILookUpAddressHyperlink;
        #endregion
    }
}
