// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.GroupDetailsPage.clickYesBtnFrmMobilityPopup_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class clickYesBtnFrmMobilityPopup_Map:logWriter
    {
        
        /// <summary>
        /// clickYesBtnFrmMobilityPopup_Method
        /// </summary>
        public void clickYesBtnFrmMobilityPopup_Method()
        {
            #region Variable Declarations
            HtmlInputButton uIYesButton = this.UIVillaPlusGroupDetailWindow.UIVillaPlusGroupDetailDocument.UIYesButton;
            #endregion

            try
            {
                // Click 'Yes' button
                Mouse.Click(uIYesButton);
                WriteLogs("PASS : Clicked \"Yes\" Button from \"Reduced mobility or wheelchair assistance\" Popup.");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could Not Click \"NO\" Button from \"Reduced mobility or wheelchair assistance\" Popup." + ex.ToString());
            }
        }

        public Boolean verifyMobilitypopupDisplay_Method()
        {
            #region Variable Declarations
            HtmlInputButton uIYesButton = this.UIVillaPlusGroupDetailWindow.UIVillaPlusGroupDetailDocument.UIYesButton;
            #endregion

            Boolean IsMobilityPopupOpened = false;
            try
            {
                IsMobilityPopupOpened = uIYesButton.TryFind();
                if (IsMobilityPopupOpened == true)
                {
                    WriteLogs("PASS : \"Reduced mobility or wheelchair assistance\" Popup is Opened.");
                }
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could Not Open \"Reduced mobility or wheelchair assistance\" Popup." + ex.ToString());
            }
            return IsMobilityPopupOpened;
        }
        #region Properties
        public UIVillaPlusGroupDetailWindow UIVillaPlusGroupDetailWindow
        {
            get
            {
                if ((this.mUIVillaPlusGroupDetailWindow == null))
                {
                    this.mUIVillaPlusGroupDetailWindow = new UIVillaPlusGroupDetailWindow();
                }
                return this.mUIVillaPlusGroupDetailWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusGroupDetailWindow mUIVillaPlusGroupDetailWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVillaPlusGroupDetailWindow : BrowserWindow
    {
        
        public UIVillaPlusGroupDetailWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Plus | Group Details");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPlusGroupDetailDocument UIVillaPlusGroupDetailDocument
        {
            get
            {
                if ((this.mUIVillaPlusGroupDetailDocument == null))
                {
                    this.mUIVillaPlusGroupDetailDocument = new UIVillaPlusGroupDetailDocument(this);
                }
                return this.mUIVillaPlusGroupDetailDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusGroupDetailDocument mUIVillaPlusGroupDetailDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVillaPlusGroupDetailDocument : HtmlDocument
    {
        
        public UIVillaPlusGroupDetailDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "book";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/booking/group-details";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/booking/group-details", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Plus | Group Details");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UIYesButton
        {
            get
            {
                if ((this.mUIYesButton == null))
                {
                    this.mUIYesButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIYesButton.SearchProperties[HtmlButton.PropertyNames.Id] = "BtnOk";
                    this.mUIYesButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Yes";
                    this.mUIYesButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIYesButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn bg-green";
                    this.mUIYesButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn bg-green\" id=\"BtnOk\" onclick=";
                    this.mUIYesButton.WindowTitles.Add("Villa Plus | Group Details");
                    #endregion
                }
                return this.mUIYesButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUIYesButton;
        #endregion
    }
}
