// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.FlightsPage.clickConfirmBtn_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class clickConfirmBtn_Map:logWriter
    {
        
        /// <summary>
        /// clickConfirmBtn_Method
        /// </summary>
        public void clickConfirmBtn_Method()
        {
            #region Variable Declarations
            HtmlHyperlink uIConfirmHyperlink = this.UIVillaPlusAmendFlightWindow.UIVillaPlusAmendFlightDocument.UIConfirmHyperlink;
            #endregion

            try
            {
                // Click 'Confirm' link
                Mouse.Click(uIConfirmHyperlink, new Point(630, 28));
                WriteLogs("PASS : Clicked \"Confirm\" Button.");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could NOT Click \"Confirm\" Button.");
                WriteLogs("--------" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public UIVillaPlusAmendFlightWindow UIVillaPlusAmendFlightWindow
        {
            get
            {
                if ((this.mUIVillaPlusAmendFlightWindow == null))
                {
                    this.mUIVillaPlusAmendFlightWindow = new UIVillaPlusAmendFlightWindow();
                }
                return this.mUIVillaPlusAmendFlightWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusAmendFlightWindow mUIVillaPlusAmendFlightWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVillaPlusAmendFlightWindow : BrowserWindow
    {
        
        public UIVillaPlusAmendFlightWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Plus | Amend Flights");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPlusAmendFlightDocument UIVillaPlusAmendFlightDocument
        {
            get
            {
                if ((this.mUIVillaPlusAmendFlightDocument == null))
                {
                    this.mUIVillaPlusAmendFlightDocument = new UIVillaPlusAmendFlightDocument(this);
                }
                return this.mUIVillaPlusAmendFlightDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusAmendFlightDocument mUIVillaPlusAmendFlightDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVillaPlusAmendFlightDocument : HtmlDocument
    {
        
        public UIVillaPlusAmendFlightDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "amendFlightBody";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/amendflight", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/booking/amendflight", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Plus | Amend Flights");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIConfirmHyperlink
        {
            get
            {
                if ((this.mUIConfirmHyperlink == null))
                {
                    this.mUIConfirmHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIConfirmHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "btnChnageDepartureAirport";
                    this.mUIConfirmHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Confirm";
                    this.mUIConfirmHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.AbsolutePath, "/booking/amendflight", PropertyExpressionOperator.Contains));
                    this.mUIConfirmHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.Href, ".villaplus.com/booking/amendflight", PropertyExpressionOperator.Contains));
                    this.mUIConfirmHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn bg-green close";
                    this.mUIConfirmHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn bg-green close\" id=\"btnChnage";
                    this.mUIConfirmHyperlink.WindowTitles.Add("Villa Plus | Amend Flights");
                    #endregion
                }
                return this.mUIConfirmHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIConfirmHyperlink;
        #endregion
    }
}
