// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.FlightsPage.clickYesFrmHoldPopup_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class clickYesFrmHoldPopup_Map:logWriter
    {
        
        /// <summary>
        /// clickYesFrmHoldPopup_Map
        /// </summary>
        public void clickYesFrmHoldPopup_Method()
        {
            #region Variable Declarations
            HtmlCustom uIConfDlgYesCustom = this.UIVillaPlusBookingInteWindow.UIVillaPlusBookingDocument.UIConfDlgYesCustom;
            #endregion
            try
            {
                // Click 'confDlgYes' custom control
                Mouse.Click(uIConfDlgYesCustom);
                WriteLogs("PASS : Clicked \"Yes\" Button from Hold Items Popup.");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could Not Click \"Yes\" Button from Hold Items Popup.");
                WriteLogs("--------" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public UIVillaPlusBookingInteWindow UIVillaPlusBookingInteWindow
        {
            get
            {
                if ((this.mUIVillaPlusBookingInteWindow == null))
                {
                    this.mUIVillaPlusBookingInteWindow = new UIVillaPlusBookingInteWindow();
                }
                return this.mUIVillaPlusBookingInteWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusBookingInteWindow mUIVillaPlusBookingInteWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaPlusBookingInteWindow : BrowserWindow
    {
        
        public UIVillaPlusBookingInteWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus | Booking", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Plus | Booking");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPlusBookingDocument UIVillaPlusBookingDocument
        {
            get
            {
                if ((this.mUIVillaPlusBookingDocument == null))
                {
                    this.mUIVillaPlusBookingDocument = new UIVillaPlusBookingDocument(this);
                }
                return this.mUIVillaPlusBookingDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusBookingDocument mUIVillaPlusBookingDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaPlusBookingDocument : HtmlDocument
    {
        
        public UIVillaPlusBookingDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "book";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus | Booking", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/booking/", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Plus | Booking");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIConfDlgYesCustom
        {
            get
            {
                if ((this.mUIConfDlgYesCustom == null))
                {
                    this.mUIConfDlgYesCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIConfDlgYesCustom.SearchProperties["TagName"] = "A";
                    this.mUIConfDlgYesCustom.SearchProperties["Id"] = "confDlgYes";
                    this.mUIConfDlgYesCustom.FilterProperties["Class"] = "btn bg-green";
                    this.mUIConfDlgYesCustom.FilterProperties["ControlDefinition"] = "class=\"btn bg-green\" id=\"confDlgYes\"";
                    this.mUIConfDlgYesCustom.WindowTitles.Add("Villa Plus | Booking");
                    #endregion
                }
                return this.mUIConfDlgYesCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIConfDlgYesCustom;
        #endregion
    }
}
