// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.FlightsPage.selectChngArrAirport_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class selectChngArrAirport_Map:logWriter
    {
        
        /// <summary>
        /// selectChngArrAirport_Method - Use 'selectChngArrAirport_MethodParams' to pass parameters into this method.
        /// </summary>
        public void selectChngArrAirport_Method()
        {
            #region Variable Declarations
            HtmlComboBox uIOptArrAirportsComboBox = this.UIVillaPlusAmendFlightWindow.UIVillaPlusAmendFlightDocument.UIOptArrAirportsComboBox;
            #endregion

            int count = uIOptArrAirportsComboBox.ItemCount;

            try
            {
                if (count > 1)
                {
                    // Select 'Faro' in 'optArrAirports' combo box
                    uIOptArrAirportsComboBox.SelectedItem = this.selectChngArrAirport_MethodParams.UIOptArrAirportsComboBoxSelectedItem;
                    WriteLogs("PASS : Changed " + uIOptArrAirportsComboBox.SelectedItem + " \"Arrival Airport\" is Selected.");
                }
                else
                {
                    WriteLogs("PASS : Could Not Change \"Arrival Airport\" as Only one Airport is Avaialable.");
                }
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could NOT Change \"Arrival Airport\".");
                WriteLogs("--------" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public virtual selectChngArrAirport_MethodParams selectChngArrAirport_MethodParams
        {
            get
            {
                if ((this.mselectChngArrAirport_MethodParams == null))
                {
                    this.mselectChngArrAirport_MethodParams = new selectChngArrAirport_MethodParams();
                }
                return this.mselectChngArrAirport_MethodParams;
            }
        }
        
        public UIVillaPlusAmendFlightWindow UIVillaPlusAmendFlightWindow
        {
            get
            {
                if ((this.mUIVillaPlusAmendFlightWindow == null))
                {
                    this.mUIVillaPlusAmendFlightWindow = new UIVillaPlusAmendFlightWindow();
                }
                return this.mUIVillaPlusAmendFlightWindow;
            }
        }
        #endregion
        
        #region Fields
        private selectChngArrAirport_MethodParams mselectChngArrAirport_MethodParams;
        
        private UIVillaPlusAmendFlightWindow mUIVillaPlusAmendFlightWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'selectChngArrAirport_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class selectChngArrAirport_MethodParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Faro' in 'optArrAirports' combo box
        /// </summary>
        public string UIOptArrAirportsComboBoxSelectedItem = "Faro";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVillaPlusAmendFlightWindow : BrowserWindow
    {
        
        public UIVillaPlusAmendFlightWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Plus | Amend Flights");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPlusAmendFlightDocument UIVillaPlusAmendFlightDocument
        {
            get
            {
                if ((this.mUIVillaPlusAmendFlightDocument == null))
                {
                    this.mUIVillaPlusAmendFlightDocument = new UIVillaPlusAmendFlightDocument(this);
                }
                return this.mUIVillaPlusAmendFlightDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusAmendFlightDocument mUIVillaPlusAmendFlightDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVillaPlusAmendFlightDocument : HtmlDocument
    {
        
        public UIVillaPlusAmendFlightDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "amendFlightBody";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/amendflight", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/booking/amendflight", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Plus | Amend Flights");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UIOptArrAirportsComboBox
        {
            get
            {
                if ((this.mUIOptArrAirportsComboBox == null))
                {
                    this.mUIOptArrAirportsComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIOptArrAirportsComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "optArrAirports";
                    this.mUIOptArrAirportsComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "id=\"optArrAirports\"";
                    this.mUIOptArrAirportsComboBox.WindowTitles.Add("Villa Plus | Amend Flights");
                    #endregion
                }
                return this.mUIOptArrAirportsComboBox;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUIOptArrAirportsComboBox;
        #endregion
    }
}
