// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.FlightsPage.verifyAmndFltsPageOpened_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class verifyAmndFltsPageOpened_Map:logWriter
    {
        
        /// <summary>
        /// verifyAmndFltsPageOpened_Method - Use 'verifyAmndFltsPageOpened_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void verifyAmndFltsPageOpened_Method()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIVillaPlusAmendFlightWindow.UIVillaPlusAmendFlightDocument.UIAmendFlight1Pane.UIItemCustom;
            #endregion

            string ActTxtFrmPage = uIItemCustom.InnerText;
            ActTxtFrmPage = ActTxtFrmPage.Replace("\r\n", "");
            ActTxtFrmPage = ActTxtFrmPage.Replace(" ", "");
            string ExpTxt = "AmendFlightDetails";
            try
            {
                StringAssert.Contains(ActTxtFrmPage, ExpTxt);
                WriteLogs("PASS : \"Amend Flights\" Page is Opened.");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could NOT Open \"Amend Flights\" Page.");
                WriteLogs("--------" + ex.Message.ToString());
            }

            // Verify that the 'InnerText' property of custom control equals 'Amend Flight Details
            //
            //
            //
            //Change Departure Airport
            //
            //
            //Filter by 
            //
            //
            //Sort by 
            //
            // '
            //Assert.AreEqual(this.verifyAmndFltsPageOpened_MethodExpectedValues.UIItemCustomInnerText, uIItemCustom.InnerText);
        }
        
        #region Properties
        public virtual verifyAmndFltsPageOpened_MethodExpectedValues verifyAmndFltsPageOpened_MethodExpectedValues
        {
            get
            {
                if ((this.mverifyAmndFltsPageOpened_MethodExpectedValues == null))
                {
                    this.mverifyAmndFltsPageOpened_MethodExpectedValues = new verifyAmndFltsPageOpened_MethodExpectedValues();
                }
                return this.mverifyAmndFltsPageOpened_MethodExpectedValues;
            }
        }
        
        public UIVillaPlusAmendFlightWindow UIVillaPlusAmendFlightWindow
        {
            get
            {
                if ((this.mUIVillaPlusAmendFlightWindow == null))
                {
                    this.mUIVillaPlusAmendFlightWindow = new UIVillaPlusAmendFlightWindow();
                }
                return this.mUIVillaPlusAmendFlightWindow;
            }
        }
        #endregion
        
        #region Fields
        private verifyAmndFltsPageOpened_MethodExpectedValues mverifyAmndFltsPageOpened_MethodExpectedValues;
        
        private UIVillaPlusAmendFlightWindow mUIVillaPlusAmendFlightWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'verifyAmndFltsPageOpened_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class verifyAmndFltsPageOpened_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of custom control equals 'Amend Flight Details
        ///
        ///
        ///
        ///Change Departure Airport
        ///
        ///
        ///Filter by 
        ///
        ///
        ///Sort by 
        ///
        /// '
        /// </summary>
        public string UIItemCustomInnerText = "Amend Flight Details\r\n\r\n\r\n\r\nChange Departure Airport\r\n\r\n\r\nFilter by \r\n\r\n\r\nSort by" +
            " \r\n\r\n ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVillaPlusAmendFlightWindow : BrowserWindow
    {
        
        public UIVillaPlusAmendFlightWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Plus | Amend Flights");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPlusAmendFlightDocument UIVillaPlusAmendFlightDocument
        {
            get
            {
                if ((this.mUIVillaPlusAmendFlightDocument == null))
                {
                    this.mUIVillaPlusAmendFlightDocument = new UIVillaPlusAmendFlightDocument(this);
                }
                return this.mUIVillaPlusAmendFlightDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusAmendFlightDocument mUIVillaPlusAmendFlightDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVillaPlusAmendFlightDocument : HtmlDocument
    {
        
        public UIVillaPlusAmendFlightDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "amendFlightBody";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/amendflight", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, "/booking/amendflight", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Plus | Amend Flights");
            #endregion
        }
        
        #region Properties
        public UIAmendFlight1Pane UIAmendFlight1Pane
        {
            get
            {
                if ((this.mUIAmendFlight1Pane == null))
                {
                    this.mUIAmendFlight1Pane = new UIAmendFlight1Pane(this);
                }
                return this.mUIAmendFlight1Pane;
            }
        }
        #endregion
        
        #region Fields
        private UIAmendFlight1Pane mUIAmendFlight1Pane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAmendFlight1Pane : HtmlDiv
    {
        
        public UIAmendFlight1Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "amendFlight1";
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.InnerText, "Back \r\n\r\n \r\nVilla Plus\r\n\r\n\r\nFilter by \r\n", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "amendFlights";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"amendFlights\" id=\"amendFlight1\"";
            this.WindowTitles.Add("Villa Plus | Amend Flights");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "SECTION";
                    this.mUIItemCustom.FilterProperties["Class"] = "booking-step";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "class=\"booking-step\"";
                    this.mUIItemCustom.WindowTitles.Add("Villa Plus | Amend Flights");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        #endregion
    }
}
