// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.FlightsPage.verifyViewSummaryOpened_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class verifyViewSummaryOpened_Map:logWriter
    {
        public void verifyViewSummaryOpened_Method()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIHttpmobstagingvillapWindow.UIHttpmobstagingvillapDocument.UIInsidesummaryPane.UIItemCustom;
            #endregion
            try
            {
                Assert.AreEqual(this.verifyViewSummaryOpened_MethodExpectedValues.UIItemCustomInnerText, uIItemCustom.InnerText);
                WriteLogs("PASS : \"View Summary\" Layer is Opened.");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could NOT Open \"View Summary\" Layer.");
                WriteLogs("--------" + ex.Message.ToString());
            }
        }
        
        #region Properties
        public virtual verifyViewSummaryOpened_MethodExpectedValues verifyViewSummaryOpened_MethodExpectedValues
        {
            get
            {
                if ((this.mverifyViewSummaryOpened_MethodExpectedValues == null))
                {
                    this.mverifyViewSummaryOpened_MethodExpectedValues = new verifyViewSummaryOpened_MethodExpectedValues();
                }
                return this.mverifyViewSummaryOpened_MethodExpectedValues;
            }
        }
        
        public UIHttpmobstagingvillapWindow UIHttpmobstagingvillapWindow
        {
            get
            {
                if ((this.mUIHttpmobstagingvillapWindow == null))
                {
                    this.mUIHttpmobstagingvillapWindow = new UIHttpmobstagingvillapWindow();
                }
                return this.mUIHttpmobstagingvillapWindow;
            }
        }
        #endregion
        
        #region Fields
        private verifyViewSummaryOpened_MethodExpectedValues mverifyViewSummaryOpened_MethodExpectedValues;
        
        private UIHttpmobstagingvillapWindow mUIHttpmobstagingvillapWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'verifyViewSummaryOpened_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class verifyViewSummaryOpened_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of custom control equals 'Your Villa Holiday
        /// '
        /// </summary>
        public string UIItemCustomInnerText = "Your Villa Holiday\r\n ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHttpmobstagingvillapWindow : BrowserWindow
    {
        
        public UIHttpmobstagingvillapWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, ".villaplus.com/booking/", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("http://mobstaging.villaplus.com/booking/");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHttpmobstagingvillapDocument UIHttpmobstagingvillapDocument
        {
            get
            {
                if ((this.mUIHttpmobstagingvillapDocument == null))
                {
                    this.mUIHttpmobstagingvillapDocument = new UIHttpmobstagingvillapDocument(this);
                }
                return this.mUIHttpmobstagingvillapDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpmobstagingvillapDocument mUIHttpmobstagingvillapDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHttpmobstagingvillapDocument : HtmlDocument
    {
        
        public UIHttpmobstagingvillapDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "book";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/booking/", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("http://mobstaging.villaplus.com/booking/");
            #endregion
        }
        
        #region Properties
        public UIInsidesummaryPane UIInsidesummaryPane
        {
            get
            {
                if ((this.mUIInsidesummaryPane == null))
                {
                    this.mUIInsidesummaryPane = new UIInsidesummaryPane(this);
                }
                return this.mUIInsidesummaryPane;
            }
        }
        #endregion
        
        #region Fields
        private UIInsidesummaryPane mUIInsidesummaryPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIInsidesummaryPane : HtmlDiv
    {
        
        public UIInsidesummaryPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "insidesummary";
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.InnerText, "Your Villa Holiday", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"insidesummary\"";
            this.WindowTitles.Add("http://mobstaging.villaplus.com/booking/");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "SECTION";
                    this.mUIItemCustom.FilterProperties["Class"] = "booking-step";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "class=\"booking-step\"";
                    this.mUIItemCustom.WindowTitles.Add("http://mobstaging.villaplus.com/booking/");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        #endregion
    }
}
