// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.FlightsPage.verifyGrpDtlsPgeOpened_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class verifyGrpDtlsPgeOpened_Map:logWriter
    {
        
        /// <summary>
        /// verifyGrpDtlsPgeOpened_Method - Use 'verifyGrpDtlsPgeOpened_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void verifyGrpDtlsPgeOpened_Method()
        {
            #region Variable Declarations
            HtmlDiv uIGroupDetailsFirstandPane = this.UIVillaPlusGroupDetailWindow.UIVillaPlusGroupDetailDocument.UIGroupDetailsFirstandPane;
            #endregion

            try
            {
                StringAssert.Contains(uIGroupDetailsFirstandPane.InnerText, this.verifyGrpDtlsPgeOpened_MethodExpectedValues.UIGroupDetailsFirstandPaneInnerText);
                WriteLogs("PASS : \"Group Details\" Page is Opened. : VERIFICATION");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Could NOT Open \"Group Details\" Page.");
                WriteLogs("--------" + ex.Message.ToString());
            }

        }
        
        #region Properties
        public virtual verifyGrpDtlsPgeOpened_MethodExpectedValues verifyGrpDtlsPgeOpened_MethodExpectedValues
        {
            get
            {
                if ((this.mverifyGrpDtlsPgeOpened_MethodExpectedValues == null))
                {
                    this.mverifyGrpDtlsPgeOpened_MethodExpectedValues = new verifyGrpDtlsPgeOpened_MethodExpectedValues();
                }
                return this.mverifyGrpDtlsPgeOpened_MethodExpectedValues;
            }
        }
        
        public UIVillaPlusGroupDetailWindow UIVillaPlusGroupDetailWindow
        {
            get
            {
                if ((this.mUIVillaPlusGroupDetailWindow == null))
                {
                    this.mUIVillaPlusGroupDetailWindow = new UIVillaPlusGroupDetailWindow();
                }
                return this.mUIVillaPlusGroupDetailWindow;
            }
        }
        #endregion
        
        #region Fields
        private verifyGrpDtlsPgeOpened_MethodExpectedValues mverifyGrpDtlsPgeOpened_MethodExpectedValues;
        
        private UIVillaPlusGroupDetailWindow mUIVillaPlusGroupDetailWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'verifyGrpDtlsPgeOpened_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class verifyGrpDtlsPgeOpened_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Group Details First and last name sho' pane contains 'Group Details'
        /// </summary>
        public string UIGroupDetailsFirstandPaneInnerText = "Group Details";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaPlusGroupDetailWindow : BrowserWindow
    {
        
        public UIVillaPlusGroupDetailWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Villa Plus | Group Details", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Plus | Group Details");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaPlusGroupDetailDocument UIVillaPlusGroupDetailDocument
        {
            get
            {
                if ((this.mUIVillaPlusGroupDetailDocument == null))
                {
                    this.mUIVillaPlusGroupDetailDocument = new UIVillaPlusGroupDetailDocument(this);
                }
                return this.mUIVillaPlusGroupDetailDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaPlusGroupDetailDocument mUIVillaPlusGroupDetailDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaPlusGroupDetailDocument : HtmlDocument
    {
        
        public UIVillaPlusGroupDetailDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "book";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Villa Plus | Group Details", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/booking/group-details", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/booking/group-details", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Plus | Group Details");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIGroupDetailsFirstandPane
        {
            get
            {
                if ((this.mUIGroupDetailsFirstandPane == null))
                {
                    this.mUIGroupDetailsFirstandPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIGroupDetailsFirstandPane.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.InnerText, "Group Details", PropertyExpressionOperator.Contains));
                    this.mUIGroupDetailsFirstandPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "wrapper";
                    this.mUIGroupDetailsFirstandPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"wrapper\"";
                    this.mUIGroupDetailsFirstandPane.WindowTitles.Add("Villa Plus | Group Details");
                    #endregion
                }
                return this.mUIGroupDetailsFirstandPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIGroupDetailsFirstandPane;
        #endregion
    }
}
