// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.SearchPage.clickBackFromHeader_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class clickBackFromHeader_Map:logWriter
    {
        
        /// <summary>
        /// clickBackFromHeader_Method
        /// </summary>
        public void clickBackFromHeader_Method()
        {
            #region Variable Declarations
            HtmlHyperlink uIBackHyperlink = this.UISearchVillaPlusWindoWindow.UISearchVillaPlusDocument.UINavtopCustom.UIBackHyperlink;
            #endregion
            
            // Click 'Back' link
            try
            {
                Mouse.Click(uIBackHyperlink);
                string chkURL = this.UISearchVillaPlusWindoWindow.Uri.ToString();
                StringAssert.Contains(chkURL, ".villaplus.com/home/index");
                WriteLogs("PASS : Clicked \"Back\" button from Header from \"Search\" Page");
            }
            catch (Exception ex)
            {
                WriteLogs("FAIL : Clould not Click \"Back\" button from Header from \"Search\" Page" + ex.ToString());
            }
        }
        
        #region Properties
        public UISearchVillaPlusWindoWindow UISearchVillaPlusWindoWindow
        {
            get
            {
                if ((this.mUISearchVillaPlusWindoWindow == null))
                {
                    this.mUISearchVillaPlusWindoWindow = new UISearchVillaPlusWindoWindow();
                }
                return this.mUISearchVillaPlusWindoWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISearchVillaPlusWindoWindow mUISearchVillaPlusWindoWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISearchVillaPlusWindoWindow : BrowserWindow
    {
        
        public UISearchVillaPlusWindoWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Search | Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Search | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UISearchVillaPlusDocument UISearchVillaPlusDocument
        {
            get
            {
                if ((this.mUISearchVillaPlusDocument == null))
                {
                    this.mUISearchVillaPlusDocument = new UISearchVillaPlusDocument(this);
                }
                return this.mUISearchVillaPlusDocument;
            }
        }
        #endregion
        
        #region Fields
        private UISearchVillaPlusDocument mUISearchVillaPlusDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISearchVillaPlusDocument : HtmlDocument
    {
        
        public UISearchVillaPlusDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "Search | Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/search", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/search", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Search | Villa Plus");
            #endregion
        }
        
        #region Properties
        public UINavtopCustom UINavtopCustom
        {
            get
            {
                if ((this.mUINavtopCustom == null))
                {
                    this.mUINavtopCustom = new UINavtopCustom(this);
                }
                return this.mUINavtopCustom;
            }
        }
        #endregion
        
        #region Fields
        private UINavtopCustom mUINavtopCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UINavtopCustom : HtmlCustom
    {
        
        public UINavtopCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "UL";
            this.SearchProperties["Id"] = "nav-top";
            this.FilterProperties.Add(new PropertyExpression("ControlDefinition", "id=\"nav-top\"", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Search | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIBackHyperlink
        {
            get
            {
                if ((this.mUIBackHyperlink == null))
                {
                    this.mUIBackHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBackHyperlink.SearchProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.InnerText, "Back ", PropertyExpressionOperator.Contains));
                    this.mUIBackHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.AbsolutePath, "showSearchTile();", PropertyExpressionOperator.Contains));
                    this.mUIBackHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.Href, "showSearchTile();", PropertyExpressionOperator.Contains));
                    this.mUIBackHyperlink.FilterProperties.Add(new PropertyExpression(HtmlHyperlink.PropertyNames.ControlDefinition, "href=\"javascript: showSearchTile();\"", PropertyExpressionOperator.Contains));
                    this.mUIBackHyperlink.WindowTitles.Add("Search | Villa Plus");
                    #endregion
                }
                return this.mUIBackHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIBackHyperlink;
        #endregion
    }
}
