// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.SearchPage.verifyDestResVillaListing_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class verifyDestResVillaListing_Map:logWriter
    {
        
        /// <summary>
        /// verifyDestResVillaListing_Method - Use 'verifyDestResVillaListing_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void verifyDestResVillaListing_Method()
        {
            #region Variable Declarations
            HtmlCustom uISearchFormCustom = this.UISearchVillaPlusWindoWindow.UISearchVillaPlusDocument.UISearchFormCustom;
            #endregion

            // Verify that the 'InnerText' property of 'searchForm' custom control contains 'Any Destination
            //Portugal
            //Algarve
            //Spain
            //Balearic Islands
            //Majorca (Mallorca)
            //Menorca (Minorca)
            //Canary Islands
            //Lanzarote
            //Fuerteventura
            //Tenerife
            //Mainland Spain
            //Costa del Sol
            //Costa Blanca
            //Greek Islands
            //Corfu
            //Kefalonia (Cephalonia)
            //Crete
            //Rhodes
            //Cyprus
            //Turkey
            //'
            try
            {
                StringAssert.Contains(uISearchFormCustom.InnerText, this.verifyDestResVillaListing_MethodExpectedValues.UISearchFormCustomInnerText, "Missing Center Name");
                WriteLogs("Destinatoin Name ok :Pass");
            }
            catch (Exception ex)
            {
                WriteLogs("Destinatoin Name ok :Fail" + ex.ToString());
            }
        }
        
        #region Properties
        public virtual verifyDestResVillaListing_MethodExpectedValues verifyDestResVillaListing_MethodExpectedValues
        {
            get
            {
                if ((this.mverifyDestResVillaListing_MethodExpectedValues == null))
                {
                    this.mverifyDestResVillaListing_MethodExpectedValues = new verifyDestResVillaListing_MethodExpectedValues();
                }
                return this.mverifyDestResVillaListing_MethodExpectedValues;
            }
        }
        
        public UISearchVillaPlusWindoWindow UISearchVillaPlusWindoWindow
        {
            get
            {
                if ((this.mUISearchVillaPlusWindoWindow == null))
                {
                    this.mUISearchVillaPlusWindoWindow = new UISearchVillaPlusWindoWindow();
                }
                return this.mUISearchVillaPlusWindoWindow;
            }
        }
        #endregion
        
        #region Fields
        private verifyDestResVillaListing_MethodExpectedValues mverifyDestResVillaListing_MethodExpectedValues;
        
        private UISearchVillaPlusWindoWindow mUISearchVillaPlusWindoWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'verifyDestResVillaListing_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class verifyDestResVillaListing_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'searchForm' custom control contains 'Any Destination
        ///Portugal
        ///Algarve
        ///Spain
        ///Balearic Islands
        ///Majorca (Mallorca)
        ///Menorca (Minorca)
        ///Canary Islands
        ///Lanzarote
        ///Fuerteventura
        ///Tenerife
        ///Mainland Spain
        ///Costa del Sol
        ///Costa Blanca
        ///Greek Islands
        ///Corfu
        ///Kefalonia (Cephalonia)
        ///Crete
        ///Rhodes
        ///Cyprus
        ///Turkey
        ///'
        /// </summary>
        public string UISearchFormCustomInnerText = @"Any Destination
Portugal
Algarve
Spain
Balearic Islands
Majorca (Mallorca)
Menorca (Minorca)
Canary Islands
Lanzarote
Fuerteventura
Tenerife
Mainland Spain
Costa del Sol
Costa Blanca
Greek Islands
Corfu
Kefalonia (Cephalonia)
Crete
Rhodes
Cyprus
Turkey
";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UISearchVillaPlusWindoWindow : BrowserWindow
    {
        
        public UISearchVillaPlusWindoWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Search | Villa Plus";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Search | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UISearchVillaPlusDocument UISearchVillaPlusDocument
        {
            get
            {
                if ((this.mUISearchVillaPlusDocument == null))
                {
                    this.mUISearchVillaPlusDocument = new UISearchVillaPlusDocument(this);
                }
                return this.mUISearchVillaPlusDocument;
            }
        }
        #endregion
        
        #region Fields
        private UISearchVillaPlusDocument mUISearchVillaPlusDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UISearchVillaPlusDocument : HtmlDocument
    {
        
        public UISearchVillaPlusDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Search | Villa Plus";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/search";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://m.villaplus.com/search";
            this.WindowTitles.Add("Search | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UISearchFormCustom
        {
            get
            {
                if ((this.mUISearchFormCustom == null))
                {
                    this.mUISearchFormCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUISearchFormCustom.SearchProperties["TagName"] = "SECTION";
                    this.mUISearchFormCustom.SearchProperties["Id"] = "searchForm";
                    this.mUISearchFormCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUISearchFormCustom.FilterProperties["Class"] = null;
                    this.mUISearchFormCustom.FilterProperties["ControlDefinition"] = "id=\"searchForm\"";
                    this.mUISearchFormCustom.FilterProperties["TagInstance"] = "2";
                    this.mUISearchFormCustom.WindowTitles.Add("Search | Villa Plus");
                    #endregion
                }
                return this.mUISearchFormCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUISearchFormCustom;
        #endregion
    }
}
