// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.HomePage.ClickSearchButton_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;


    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class ClickSearchButton_Map:logWriter
    {
        
        /// <summary>
        /// ClickSearchButton_Method
        /// </summary>
        public void ClickSearchButton_Method()
        {
            #region Variable Declarations
            HtmlHyperlink uISearchVillasHyperlink = this.UIVillaHolidaysThatYouWindow.UIVillaHolidaysThatYouDocument.UIHomepagePane.UISearchVillasHyperlink;
            #endregion

            // Click 'Search Villas' link
            Mouse.Click(uISearchVillasHyperlink, new Point(741, 42));
            string checkurl = this.UIVillaHolidaysThatYouWindow.Uri.ToString();
            if (checkurl.Contains("search"))
            {
                WriteLogs(checkurl + " URL opened Succssefully " + checkurl + ":Pass");
                
            }
            else 
            {
                WriteLogs(" Search URL NOT opened:Fail ");
            }
            this.UIVillaHolidaysThatYouWindow.Back ();
        }
        
        #region Properties
        public UIVillaHolidaysThatYouWindow UIVillaHolidaysThatYouWindow
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouWindow == null))
                {
                    this.mUIVillaHolidaysThatYouWindow = new UIVillaHolidaysThatYouWindow();
                }
                return this.mUIVillaHolidaysThatYouWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaHolidaysThatYouWindow mUIVillaHolidaysThatYouWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouWindow : BrowserWindow
    {
        
        public UIVillaHolidaysThatYouWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Villa Holidays That You’ll Love More | Villa Plus";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaHolidaysThatYouDocument UIVillaHolidaysThatYouDocument
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouDocument == null))
                {
                    this.mUIVillaHolidaysThatYouDocument = new UIVillaHolidaysThatYouDocument(this);
                }
                return this.mUIVillaHolidaysThatYouDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaHolidaysThatYouDocument mUIVillaHolidaysThatYouDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouDocument : HtmlDocument
    {
        
        public UIVillaHolidaysThatYouDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Villa Holidays That You’ll Love More | Villa Plus";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://m.villaplus.com/";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public UIHomepagePane UIHomepagePane
        {
            get
            {
                if ((this.mUIHomepagePane == null))
                {
                    this.mUIHomepagePane = new UIHomepagePane(this);
                }
                return this.mUIHomepagePane;
            }
        }
        #endregion
        
        #region Fields
        private UIHomepagePane mUIHomepagePane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHomepagePane : HtmlControl
    {
        
        public UIHomepagePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.ControlType] = "Pane";
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "homepage";
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.InnerText, "Homepage\r\n\r\n\r\n\r\n\r\n\r\n \r\n\r\n2015 is here!\r\n", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"homepage\"";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UISearchVillasHyperlink
        {
            get
            {
                if ((this.mUISearchVillasHyperlink == null))
                {
                    this.mUISearchVillasHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISearchVillasHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUISearchVillasHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUISearchVillasHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUISearchVillasHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Search Villas ";
                    this.mUISearchVillasHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/search";
                    this.mUISearchVillasHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUISearchVillasHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://m.villaplus.com/search";
                    this.mUISearchVillasHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn bg-green";
                    this.mUISearchVillasHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn bg-green\" href=\"/search\"";
                    this.mUISearchVillasHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUISearchVillasHyperlink.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
                    #endregion
                }
                return this.mUISearchVillasHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUISearchVillasHyperlink;
        #endregion
    }
}
