// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.HomePage.verifyIncompleteBkgPopupDisplay_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class verifyIncompleteBkgPopupDisplay_Map:logWriter
    {
        
        /// <summary>
        /// verifyIncompleteBkgPopupDisplay_Method - Use 'verifyIncompleteBkgPopupDisplay_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public Boolean verifyIncompleteBkgPopupDisplay_Method()
        {
            #region Variable Declarations
            HtmlDiv uIInComBookPane = this.UIVillaHolidaysThatYouWindow.UIVillaHolidaysThatYouDocument.UIInComBookPane;
            #endregion
            Boolean IspopupExists = false;
            try
            {
                HtmlCustom section = new HtmlCustom(uIInComBookPane);
                section.SearchProperties["class"] = "pad-clr";
                HtmlCustom ul = new HtmlCustom(section);
                ul.SearchProperties["class"] = "dialogDetails";
                HtmlHyperlink li = new HtmlHyperlink(ul);
                li.SearchProperties["class"] = "btn bg-orange";
                li.SearchProperties["id"] = "No";
                IspopupExists = li.TryFind();
                if (IspopupExists == true)
                {
                    WriteLogs("INFO : InComplete Booking Popup Displayed.");
                }
            }
            catch(Exception ex)
            {
                IspopupExists = false;
                WriteLogs("INFO : InComplete Booking Popup Not Displayed.");
                WriteLogs("--------" + ex.Message.ToString());
            }
            return IspopupExists;
        }
        
        #region Properties
        public virtual verifyIncompleteBkgPopupDisplay_MethodExpectedValues verifyIncompleteBkgPopupDisplay_MethodExpectedValues
        {
            get
            {
                if ((this.mverifyIncompleteBkgPopupDisplay_MethodExpectedValues == null))
                {
                    this.mverifyIncompleteBkgPopupDisplay_MethodExpectedValues = new verifyIncompleteBkgPopupDisplay_MethodExpectedValues();
                }
                return this.mverifyIncompleteBkgPopupDisplay_MethodExpectedValues;
            }
        }
        
        public UIVillaHolidaysThatYouWindow UIVillaHolidaysThatYouWindow
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouWindow == null))
                {
                    this.mUIVillaHolidaysThatYouWindow = new UIVillaHolidaysThatYouWindow();
                }
                return this.mUIVillaHolidaysThatYouWindow;
            }
        }
        #endregion
        
        #region Fields
        private verifyIncompleteBkgPopupDisplay_MethodExpectedValues mverifyIncompleteBkgPopupDisplay_MethodExpectedValues;
        
        private UIVillaHolidaysThatYouWindow mUIVillaHolidaysThatYouWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'verifyIncompleteBkgPopupDisplay_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class verifyIncompleteBkgPopupDisplay_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'InComBook' pane contains 'Incomplete Booking'
        /// </summary>
        public string UIInComBookPaneInnerText = "Incomplete Booking";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouWindow : BrowserWindow
    {
        
        public UIVillaHolidaysThatYouWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "| Villa Plus", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaHolidaysThatYouDocument UIVillaHolidaysThatYouDocument
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouDocument == null))
                {
                    this.mUIVillaHolidaysThatYouDocument = new UIVillaHolidaysThatYouDocument(this);
                }
                return this.mUIVillaHolidaysThatYouDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaHolidaysThatYouDocument mUIVillaHolidaysThatYouDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouDocument : HtmlDocument
    {
        
        public UIVillaHolidaysThatYouDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.Title, "| Villa Plus", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.AbsolutePath, "/", PropertyExpressionOperator.Contains));
            this.FilterProperties.Add(new PropertyExpression(HtmlDocument.PropertyNames.PageUrl, ".villaplus.com/", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIInComBookPane
        {
            get
            {
                if ((this.mUIInComBookPane == null))
                {
                    this.mUIInComBookPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIInComBookPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "InComBook";
                    this.mUIInComBookPane.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.InnerText, "Incomplete Booking", PropertyExpressionOperator.Contains));
                    this.mUIInComBookPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "infoBoxContent lightbox";
                    this.mUIInComBookPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"infoBoxContent lightbox\" id=\"InComBook\" style=\"left: 590px; top: 50px; wid" +
                        "th: 200px; height: 200px; right: 590px; display: block;\" data-infobox=\"info-defa" +
                        "ult\"";
                    this.mUIInComBookPane.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
                    #endregion
                }
                return this.mUIInComBookPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIInComBookPane;
        #endregion
    }
}
