// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTestAutomation.UIMap.HomePage.verifyHomePageText_MapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    using MobileTestAutomation.Utility;
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class verifyHomePageText_Map:logWriter
    {
        
        /// <summary>
        /// verifyHomePageText_Method - Use 'verifyHomePageText_MethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void verifyHomePageText_Method()
        {
            #region Variable Declarations
            HtmlDiv uIWemakesureyouloveitmPane = this.UIVillaHolidaysThatYouWindow.UIVillaHolidaysThatYouDocument.UIHomepagePane.UIWemakesureyouloveitmPane;
            #endregion

            // Verify that the 'InnerText' property of 'We make sure you love it more - all our' pane equals 'We make sure you love it more - all our villas typically include all this...FREE
            //
            //British Travel Awards 2013
            //Private Pools
            //Air con/heating
            //Pool heating
            //CD & DVD Player
            //Pool Table
            //Table Tennis Table
            //WiFi (in over half of our villas)
            //BBQ
            //Washing Machine
            //Satellite TV
            //Dishwasher & Microwave!
            //Maid & Linen service
            //Friendly, experienced in-resort staff
            //
            //Plus! Pool fences available by request at an extra cost at over 200 villas'
            try
            {
                Assert.AreEqual(this.verifyHomePageText_MethodExpectedValues.UIWemakesureyouloveitmPaneInnerText, uIWemakesureyouloveitmPane.InnerText);
                WriteLogs("Home Page Verification : Pass");
            }
            catch (Exception ex)
            {
                WriteLogs("Home Page Verification : Fail" + ex);
            }
        }
        
        #region Properties
        public virtual verifyHomePageText_MethodExpectedValues verifyHomePageText_MethodExpectedValues
        {
            get
            {
                if ((this.mverifyHomePageText_MethodExpectedValues == null))
                {
                    this.mverifyHomePageText_MethodExpectedValues = new verifyHomePageText_MethodExpectedValues();
                }
                return this.mverifyHomePageText_MethodExpectedValues;
            }
        }
        
        public UIVillaHolidaysThatYouWindow UIVillaHolidaysThatYouWindow
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouWindow == null))
                {
                    this.mUIVillaHolidaysThatYouWindow = new UIVillaHolidaysThatYouWindow();
                }
                return this.mUIVillaHolidaysThatYouWindow;
            }
        }
        #endregion
        
        #region Fields
        private verifyHomePageText_MethodExpectedValues mverifyHomePageText_MethodExpectedValues;
        
        private UIVillaHolidaysThatYouWindow mUIVillaHolidaysThatYouWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'verifyHomePageText_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class verifyHomePageText_MethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'We make sure you love it more - all our' pane equals 'We make sure you love it more - all our villas typically include all this...FREE
        ///
        ///British Travel Awards 2013
        ///Private Pools
        ///Air con/heating
        ///Pool heating
        ///CD & DVD Player
        ///Pool Table
        ///Table Tennis Table
        ///WiFi (in over half of our villas)
        ///BBQ
        ///Washing Machine
        ///Satellite TV
        ///Dishwasher & Microwave!
        ///Maid & Linen service
        ///Friendly, experienced in-resort staff
        ///
        ///Plus! Pool fences available by request at an extra cost at over 200 villas'
        /// </summary>
        public string UIWemakesureyouloveitmPaneInnerText = @"We make sure you love it more - all our villas typically include all this...FREE

British Travel Awards 2013
Private Pools
Air con/heating
Pool heating
CD & DVD Player
Pool Table
Table Tennis Table
WiFi (in over half of our villas)
BBQ
Washing Machine
Satellite TV
Dishwasher & Microwave!
Maid & Linen service
Friendly, experienced in-resort staff

Plus! Pool fences available by request at an extra cost at over 200 villas";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouWindow : BrowserWindow
    {
        
        public UIVillaHolidaysThatYouWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Villa Holidays That You’ll Love More | Villa Plus";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIVillaHolidaysThatYouDocument UIVillaHolidaysThatYouDocument
        {
            get
            {
                if ((this.mUIVillaHolidaysThatYouDocument == null))
                {
                    this.mUIVillaHolidaysThatYouDocument = new UIVillaHolidaysThatYouDocument(this);
                }
                return this.mUIVillaHolidaysThatYouDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIVillaHolidaysThatYouDocument mUIVillaHolidaysThatYouDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIVillaHolidaysThatYouDocument : HtmlDocument
    {
        
        public UIVillaHolidaysThatYouDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Villa Holidays That You’ll Love More | Villa Plus";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "/";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public UIHomepagePane UIHomepagePane
        {
            get
            {
                if ((this.mUIHomepagePane == null))
                {
                    this.mUIHomepagePane = new UIHomepagePane(this);
                }
                return this.mUIHomepagePane;
            }
        }
        #endregion
        
        #region Fields
        private UIHomepagePane mUIHomepagePane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIHomepagePane : HtmlDiv
    {
        
        public UIHomepagePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "homepage";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.InnerText, "Homepage\r\n\r\n\r\n\r\n\r\n\r\n \r\n\r\n2015 is here!\r\n", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = "";
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "";
            this.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.ControlDefinition, "id=\"homepage\"", PropertyExpressionOperator.Contains));
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
            this.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIWemakesureyouloveitmPane
        {
            get
            {
                if ((this.mUIWemakesureyouloveitmPane == null))
                {
                    this.mUIWemakesureyouloveitmPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIWemakesureyouloveitmPane.FilterProperties.Add(new PropertyExpression(HtmlDiv.PropertyNames.InnerText, "We make sure you love it more - all our ", PropertyExpressionOperator.Contains));
                    this.mUIWemakesureyouloveitmPane.FilterProperties[HtmlDiv.PropertyNames.Title] = "";
                    this.mUIWemakesureyouloveitmPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "wrapper border-blue";
                    this.mUIWemakesureyouloveitmPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"wrapper border-blue\"";
                    this.mUIWemakesureyouloveitmPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "14";
                    this.mUIWemakesureyouloveitmPane.WindowTitles.Add("Villa Holidays That You’ll Love More | Villa Plus");
                    #endregion
                }
                return this.mUIWemakesureyouloveitmPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIWemakesureyouloveitmPane;
        #endregion
    }
}
